export const gbpLocation = {
  storeName: "Queen Lansdowne Cannabis",
  domain: "www.queenlansdownecannabis.ca",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "1472 Queen St W, Toronto, ON M6K 1M4",
  streetAddress: "1472 Queen St W",
  postalCode: "M6K 1M4",
  phone: "(647) 553-1472",
  phoneIntl: "+16475531472",
  neighborhood: "Queen West / Lansdowne / Parkdale",
  nearbyAreas: ["Queen Street West", "Lansdowne", "Parkdale", "Little Portugal", "Roncesvalles", "Brockton Village", "Dundas West", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.6406611",
  longitude: "-79.4370110",
  hours: ["Open Daily: 10:00 AM - 03:00 AM"],
  seoTitle: "Queen Lansdowne Cannabis | Weed Dispensary in Toronto",
  metaDescription: "Queen Lansdowne Cannabis is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Queen Street West", "Lansdowne", "Parkdale"],
  introVariant: "Queen Lansdowne Cannabis is a local weed dispensary in Toronto, located at 1472 Queen St W. We serve adults 19+ looking for quality weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, shatter, CBD oils, and accessories. Whether you are searching for a weed dispensary near Queen West / Lansdowne / Parkdale, a cannabis store in Toronto, or a local weed shop close to Lansdowne, our friendly team is here to help you find the right product.",
  neighborhoodDescription: "Located in the vibrant Queen West / Lansdowne / Parkdale district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking is available along Queen Street West",
  transitNote: "Served by the 501 Queen streetcar and local Lansdowne TTC routes.",
  sectionTitle: "Serving Customers Near Queen West and Lansdowne"
};
