"use client";
import Image from "next/image";
import { type ReactNode, useEffect, useId, useRef } from "react";
export type DetailProduct={publicProductId:string;name:string;tier:string;category:string;strain:string;thc:string;effects:string[];description:string|null;images:string[]};
export default function ProductDetailsDrawer({product,storeName,pricing,onClose}:{product:DetailProduct|null;storeName:string;pricing:ReactNode;onClose:()=>void}){
 const titleId=useId();const drawerRef=useRef<HTMLElement>(null);const closeRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!product)return;const prior=document.activeElement instanceof HTMLElement?document.activeElement:null;const overflow=document.body.style.overflow;document.body.style.overflow="hidden";closeRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){onClose();return;}if(event.key!=="Tab")return;const focusable=[...(drawerRef.current?.querySelectorAll<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')||[])].filter(item=>!item.hasAttribute("disabled"));if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=overflow;prior?.focus();};},[product,onClose]);
 if(!product)return null;return <div className="product-detail-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section ref={drawerRef} className="product-detail-drawer" role="dialog" aria-modal="true" aria-labelledby={titleId}><header className="product-detail-header"><div><span>{storeName}</span><strong>Product details</strong></div><button ref={closeRef} type="button" onClick={onClose} aria-label="Close product details">{"\u00D7"}</button></header><div className="product-detail-content">{product.images[0]&&<div className="product-detail-image"><Image src={product.images[0]} alt={product.name} fill sizes="(max-width:720px) 100vw,420px"/></div>}<div className="product-detail-badges"><span>{product.tier}</span><span>{product.strain||product.category}</span></div><h2 id={titleId}>{product.name}</h2>{product.category&&<p>{product.category}</p>}{product.thc&&<p><strong>Source-provided THC:</strong> {product.thc}</p>}{product.effects.length>0&&<div className="product-detail-effects" aria-label="Source-provided effects">{product.effects.map(effect=><span key={effect}>{effect}</span>)}</div>}<p className="product-detail-description">{product.description||"Ask the dispatcher for more product details."}</p><div className="product-detail-pricing">{pricing}</div></div></section></div>;
}
